import { addStrings } from 'meteor/vulcan:core';

addStrings('hu', {

  "accounts.error_emailRequired": "Az email kötelező",
  "accounts.error_invalid_email": "Nem megfelelő email",
  "accounts.error_minchar": "A jelszó túl rövid",
  "accounts.error_username_required": "A felhasználó név kötelező",
  "accounts.error_accounts_": "",
  "accounts.error_unknown": "Ismeretlen hiba",
  "accounts.enter_username_or_email": "Adja meg a felhasználónevet vagy az email címet",
  "accounts.username_or_email": "Felhasználónév vagy email",
  "accounts.enter_username": "Adja meg a felhasználónevet",
  "accounts.username": "Felhasználónév",
  "accounts.enter_email": "Adja meg az email címet",
  "accounts.email": "Email",
  "accounts.enter_password": "Adja meg a jelszót",
  "accounts.password": "Jelszó",
  "accounts.choose_password": "Válasszon jelszót",
  "accounts.change_password": "Jelszó megváltoztatása",
  "accounts.reset_your_password": "Jelszó újra létrehozása",
  "accounts.set_password": "Jelszó megadása",
  "accounts.enter_new_password": "Új jelszó megadása",
  "accounts.new_password": "Új jelszó",
  "accounts.forgot_password": "Elfelejtett jelszó",
  "accounts.sign_up": "Regisztráció",
  "accounts.sign_in": "Bejelentkezés",
  "accounts.sign_out": "Kijelentkezés",
  "accounts.cancel": "mégsem",
  "accounts.or_use": "vagy használata",
  "accounts.info_email_sent": "Email elküldve.",
  "accounts.info_password_changed": "A jelszó megváltoztatva.",
  "accounts.logging_in": "Bejelentkezés…",

  "forms.submit": "Ment",
  "forms.cancel": "Mégsem",
  "forms.select_option": "-- lehetőség választása --",
  "forms.delete": "Törlés",
  "forms.delete_confirm": "Dokumentum törlése?",
  
  "posts.new_post": "Új bejegyzés",
  "posts.edit": "Szerkesztés",
  "posts.edit_success": "“{title}” bejegyzés elmentve.",
  "posts.delete": "Törlés",
  "posts.delete_confirm": "“{title}” törlése?",
  "posts.delete_success": "“{title}” törölve.",
  "posts.title": "Cím",
  "posts.url": "URL",
  "posts.body": "Szöveg",
  "posts.categories": "Kategóriák",
  "posts.thumbnailUrl": "Bélyegkép URL",
  "posts.status": "Státusz",
  "posts.sticky": "Kitűzve",
  "posts.load_more": "Több betöltése",
  "posts.load_more_days": "Több nap betöltése",
  "posts.no_more": "Nincs több bejegyzés.",
  "posts.no_results": "Nincs bejegyzés.",
  "posts.search": "Keresés",
  "posts.view": "Mutat",
  "posts.top": "Legnézettebb",
  "posts.new": "Új",
  "posts.best": "Legjobb",
  "posts.pending": "Függőben",
  "posts.rejected": "Visszautasítva",
  "posts.scheduled": "Ütemezve",
  "posts.daily": "Napi",
  "posts.clear_thumbnail": "Bélyegkép törlése",
  "posts.enter_thumbnail_url": "URL megadása",
  "posts.created_message": "Bejegyzés létrehozva.",
  "posts.rate_limit_error": "Kérem várjon {value} másodpercet a következő küldés előtt!",
  "posts.postedAt": "Létrehozva",
  "posts.dateNotDefined": "A dátum nincs megadva!",
  "posts.subscribe": "Feliratkozás",
  "posts.unsubscribe": "Leiratkozás",
  "posts.subscribed": "Feliratkozott a(z) “{name}” comments.",
  "posts.unsubscribed": "You have unsubscribed from “{name}” megjegyzésre.",
  "posts.subscribed_posts" : "Bejegyzésre feliratkozva",
  "posts.link_already_posted": "Ezt a linket már közzétették.",
  "posts.max_per_day": "Sajnálom, de egy nap legfeljebb {value} bejegyzést tehet közzzé.",

  "comments.comments": "Megjegyzések",
  "comments.count": "{count, plural, =0 {Nincs megjegyzés} egy {# megjegyzés} több {# megjegyzés}}",
  "comments.new": "Új megjegyzés",
  "comments.no_comments": "Nincs megjegyzés.",
  "comments.reply": "Válasz",
  "comments.edit": "Szerkesztés",
  "comments.delete": "Törlés",
  "comments.delete_confirm": "Megjegyzés törlése?",
  "comments.delete_success": "Megjegyzés törölve.",
  "comments.please_log_in": "Megjegyzés írásához, kérem, jelentkezzen be!",
  "comments.parentCommentId": "Szülő megjegyzés azonosító",
  "comments.topLevelCommentId": "Felső szintű megjegyzés azonosító",
  "comments.body": "Szöveg",
  "comments.rate_limit_error": "Kérem várjon {value} másodpercet a következő küldés előtt!",

  "users.profile": "Adatlap",
  "users.complete_profile": "Töltese ki az Adatlapot",
  "users.profile_completed": "Adatlap kész.",
  "users.edit_account": "Fiók szerkesztése",
  "users.edit_success": "“{name}” felhasználó mentve",
  "users.log_in": "Bejelentkezés",
  "users.sign_up": "Regisztráció",
  "users.log_out": "Kijelentkezés",
  "users.bio": "Életrajz",
  "users.displayName": "Megjelenítendő név",
  "users.email": "Email",
  "users.twitterUsername": "Twitter felhasználó név",
  "users.website": "Weboldal",
  "users.groups": "Csoportok",
  "users.avatar": "Avatar",
  "users.notifications": "Értesítések",
  "users.notifications_users": "Értesítés új felhasználókról",
  "users.notifications_posts": "Értesítés új bejegyzésekről",
  "users.newsletter_subscribeToNewsletter": "Feliratkozás a hírlevélre",
  "users.admin": "Admin",
  "users.isAdmin": "Admin",
  "users.posts": "Bejegyzések",
  "users.please_log_in": "Kérem, jelentkezzen be",
  "users.cannot_post": "Sajnálom, de most nincs megfelelő jogosultsága bejegyzés létrehozásához",
  "users.cannot_comment": "Sajnálom, de most nincs megfelelő jogosultsága megjegyzés létrehozásához",
  "users.subscribe": "Feliratkozás a felhasználó bejegyzéseire",
  "users.unsubscribe": "Leiratkozás a felhasználó megjegyzéseiről",
  "users.subscribed": "Feliratkozott “{name}” felhasználó bejegyzéseire.",
  "users.unsubscribed": "Leiratkozott “{name}” felhasználó bejegyzéseiről.",
  "users.subscribers": "Feliratkozva",
  "users.delete": "Felhasználó törlése",
  "users.delete_confirm": "Felhasználó törlése?",
  "users.email_already_taken": "Ez az email már létezik: {value}",

  "categories": "Kategóriák",
  "categories.all": "Összes kategória",
  "categories.edit": "Kategória szerkesztése",
  "categories.edit_success": "“{name}” kategória szerkesztve.",
  "categories.new": "Új kategória",
  "categories.new_success": "“{name}” kategória létrehozva.",
  "categories.delete": "Kategória törlése",
  "categories.name": "Megnevezés",
  "categories.description": "Leírás",
  "categories.order": "Sorrend",
  "categories.slug": "Slug",
  "categories.image": "Kép",
  "categories.parentId": "Szülő azonosító",
  "categories.subscribe": "Feliratkozás a kategória bejegyzéseire",
  "categories.unsubscribe": "Lairatkozás a kategória bejegyzéseiről",
  "categories.subscribed": "Feliratkozott a(z) “{name}” kategória bejegyzéseire.",
  "categories.unsubscribed": "Lairatkozott a(z) “{name}” kategória bejegyzéseire.",
  "categories.subscribed_categories" : "Feliratkozott kategóriák",
  "categories.delete_confirm": "“{title}” kategória törlése?",
  "categories.delete_success": "“{name}” kategória törölve.",
  "categories.invalid": "Érvénytelen kategória",

  "settings": "Beállítások",
  "settings.json_message": "Note: settings already provided in your <code>settings.json</code> file will be disabled.",
  "settings.edit": "Beállítások szerkesztése",
  "settings.edited": "Beállítások elmentve (kérem frissítsen).",
  "settings.title": "Cím",
  "settings.siteUrl": "Honlap URL",
  "settings.tagline": "Tag-ek",
  "settings.description": "Leírás",
  "settings.siteImage": "Honlap kép",
  "settings.defaultEmail": "Alapértelmezett email",
  "settings.mailUrl": "Email URL",
  "settings.scoreUpdate": "Pont frissítés",
  "settings.postInterval": "Bejegyzés időköz",
  "settings.RSSLinksPointTo": "RSS link",
  "settings.commentInterval": "Megjegyzés időköz",
  "settings.maxPostsPerDay": "Max bejegyzése naponta.",
  "settings.startInvitesCount": "Meghívások számláló indítása",
  "settings.postsPerPage": "Bejegyzések oldalanként",
  "settings.logoUrl": "Logo URL",
  "settings.logoHeight": "Logo magasság",
  "settings.logoWidth": "Logo szélesség",
  "settings.faviconUrl": "Favicon URL",
  "settings.twitterAccount": "Twitter felhasználó",
  "settings.facebookPage": "Facebook oldal",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "Nyelv",
  "settings.requireViewInvite": "Megtekintés meghívás szükséges",
  "settings.requirePostInvite": "Bejegyzés meghívás szükséges",
  "settings.requirePostsApproval": "Bejegyzés elfogadása szükséges",
  "settings.scoreUpdateInterval": "Pontszám frissítési időköz",

  "app.loading": "Betöltés…",
  "app.404": "Sajnálom, a keresett oldalt nem találjuk.",
  "app.powered_by": "Powered by Telescope",
  "app.or": "vagy",
  "app.noPermission": "Sorry, you do not have the permission to do this at this time.",
  "app.operation_not_allowed": 'Sorry, you don\'t have the rights to perform the operation "{value}"',
  "app.disallowed_property_detected": "Disallowed property detected: {value}",
  "app.something_bad_happened": "Something bad happened...",
  "app.embedly_not_authorized": "Invalid Embedly API key provided in the settings file. To find your key, log into https://app.embed.ly -> API",
  
  "newsletter": "Hírlevél",
  "newsletter.subscribe": "Feliratkozás",
  "newsletter.unsubscribe": "Leiratkozás",
  "newsletter.subscribe_prompt": "Feliratkozás a hírlevélre",
  "newsletter.email": "Az email címe",
  "newsletter.success_message": "Köszönjük, hogy feliratkozott!",
  "newsletter.subscription_updated": "Hírlevél feliratkozás frissítve..",
  "newsletter.subscription_failed": "Sikertelen feliratkozás. A Mailchimp megfelelően be van állítva a beállítások fájlban?",

  "admin": "Admin",
  "notifications": "Értesítések",
});
